### ISSUE TITLE
Consolidate with official Spring Boot 2.0 starter project

### ISSUE THREAD

**Issue by georgwittberger** [andrehertwig/spring-boot-starter-quartz#1]
There will be an official Spring Boot starter for Quartz with Spring Boot 2.0. See: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0.0-M2-Release-Notes#quartz-scheduler

Maybe you should get involved in development there if you find that previous starters (especially their auto-configuration) did not meet your requirements.

Have a look here: https://github.com/spring-projects/spring-boot/tree/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/quartz

**Comment by andrehertwig** [comment]
Thanks for the information.
Seems that they thought on SchedulerFactory customizers (what's called *OverrideHook in my implementation).
